services:

  api:
    build:
      context: .
      dockerfile: src/diabetes_prediction/api/Dockerfile
    container_name: diabetes_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - diabetes-network

  app:
    build:
      context: .
      dockerfile: src/diabetes_prediction/app/Dockerfile
    container_name: diabetes_app
    restart: unless-stopped
    ports:
      - "8501:8501"
    networks:
      - diabetes-network
    depends_on:
      - api

  prometheus:
    image: dhi.io/prometheus:3.11
    container_name: diabetes_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - diabetes-network
    depends_on:
      - api

networks:
  diabetes-network:
    driver: bridge
