[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "diabetes-prediction"
version = "0.1.0"
description = "An end-to-end ML system for predicting diabetes with strict operation policies"
requires-python = ">=3.12"
license = "MIT"
authors = [
    { name = "babaksoft", email = "babak.eslamieh@gmail.com" },
]
keywords = ["machine learning", "classification"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "joblib",
    "mlflow",
    "numpy",
    "pandas",
    "prometheus-client",
    "scikit-learn",
]

[project.optional-dependencies]
train = [
    "boto3",
    "dvc[s3]",
    "matplotlib",
    "python-dotenv",
    "sagemaker",
    "shap",
    "tqdm",
]

build = [
    "build",
    "hatchling",
]

dev = [
    "black",
    "ipykernel",
    "isort",
    "mypy",
    "pytest",
    "ruff",
]

api = [
    "fastapi",
    "uvicorn",
]

app = [
    "requests",
    "streamlit",
]

[project.urls]
Homepage = "https://github.com/babaksoft/diabetes-prediction"
Issues = "https://github.com/babaksoft/diabetes-prediction/issues"

[tool.black]
target-version = ["py312"]

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]

[tool.ruff]
src = ["src", "tests"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.hatch.build]
sources = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/diabetes_prediction"]
