[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "diabetes-prediction"
version = "0.1.0"
description = "An end-to-end ML system for predicting diabetes with strict operation policies"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    { name = "babaksoft", email = "babak.eslamieh@gmail.com" },
]
keywords = ["machine learning", "classification"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license-files = ["LICEN[CS]E*"]

dependencies = [
    "boto3",
    "joblib",
    "matplotlib",
    "mlflow",
    "numpy",
    "pandas",
    "python-dotenv",
    "sagemaker",
    "scikit-learn",
    "tqdm",
]

[project.optional-dependencies]
build = [
    "build",
    "hatchling",
]

dev = [
    "black",
    "isort",
    "mypy",
    "pytest",
    "ruff",
]

api = [
    "fastapi",
    "joblib",
    "numpy",
    "pandas",
    "scikit-learn",
    "uvicorn",
]

app = [
    "requests",
    "streamlit",
]

[project.urls]
Homepage = "https://github.com/babaksoft/diabetes-prediction"
Issues = "https://github.com/babaksoft/diabetes-prediction/issues"

[tool.isort]
profile = "black"

[tool.hatch.build]
exclude = [
    "/.dvc",
    "**/*.dvc",
    "**/.gitignore",
    "/notebooks",
    "/tests",
    ".gitignore",
    ".dvcignore",
    "requirements.txt"
]
